// mutations
export const UPDATEUSER = 'updateUser'
export const UPDATEPINS = 'updatePins'
export const UPDATEPAGENUM = 'updatePageNumber'
export const RESETDATA = 'resetData'
export const SEARCHTEXT = 'searchText'
// actions
export const LOGIN = 'login'
export const SIGNUP = 'signup'
export const LOGOUT = 'logout'
export const ISAUTH = 'isAuth'
export const GETPINS = 'getPins'
export const FETCHPINBYID = 'fetchPinById'
export const UPLOADFILE = 'uploadFile'
export const GETOWNPINS = 'getOwnPins'
export const DELPINBYID = 'deletePinById'
export const SEARCHPINS = 'searchPins'
export const UPDATEPINBYID = 'updatePinById'
